# To use:
#   $ conda env create -f environment.yml
#   $ conda activate graphblas-algorithms-dev
#
# Or use mamba instead of conda.
#
# pre-commit should be set up once after the repo is cloned (see .pre-commit-config.yaml).
# In the `graphblas-algorithms-dev` environment, run:
#   $ pre-commit install
#
# At times, one may need to use a development version of networkx or python-graphblas.
# To do this, you will need to uninstall, git clone, and run setup.py develop.  For example:
#
#   $ conda remove --force python-graphblas
#   $ git clone git@github.com:python-graphblas/python-graphblas.git
#   $ cd python-graphblas
#   $ python setup.py develop --no-deps
#
#   $ conda remove --force networkx
#   $ git clone git@github.com:networkx/networkx.git
#   $ cd networkx
#   $ python setup.py develop --no-deps
name: graphblas-algorithms-dev
channels:
    - conda-forge
    - nodefaults  # Only install packages from conda-forge for faster solving
dependencies:
    - python
    - python-graphblas
    - networkx
    # python-graphblas default dependencies
    - donfig
    - numba
    - python-suitesparse-graphblas
    - pyyaml
    # python-graphblas extra dependencies
    - fast_matrix_market
    - packaging
    # networkx default dependencies
    - matplotlib
    - pandas
    - scipy
    # networkx extra dependencies
    - lxml
    - pydot
    - pygraphviz
    - sympy
    # For updating algorithm list in README
    - rich
    # For linting
    - pre-commit
    # For testing
    - pytest-cov
    # For benchmarking
    - requests
    # For debugging
    - icecream
    - ipykernel
    - ipython
    # For type annotations
    - mypy
    # For benchmark comparisons (optional; uncomment as desired)
    # - igraph
    # - python-igraph
    # - networkit
    # - graph-tool
    # - xorg-libxcursor  # for graph-tool
